### PR TITLE
[Core/PhaseSystem] Update Quest Phase System to enable phase handling…

### PR DESCRIPTION
**Pull request by kuramajssken001**
achieve world quest phase.

### CODE REVIEW

**Comment by kuramajssken001** [comment]
https://www.youtube.com/watch?v=_eFVEkB9XX4

**Comment by DevPrimeR** [comment]
Hi, The phase system does not work? I don't have the project compiled but I think the correct operation is using spells_areas (if the quest has them) or using the phases definitions system and controlling it with conditions.

**Comment by kuramajssken001** [comment]
> Hi, The phase system does not work? I don't have the project compiled but I think the correct operation is using spells_areas (if the quest has them) or using the phases definitions system and controlling it with conditions.

https://www.youtube.com/watch?v=_eFVEkB9XX4 look this

**Comment by alexkulya** [comment]
@kuramajssken001
Some additions needed:
Abercrombie - combat text.
Deleting standard stitch spawns with Abercrombie and guards.
Adding doubles in phase 1 for creatures from phases 3 and 2?

**Comment by kuramajssken001** [comment]
> @kuramajssken001 Some additions needed: Abercrombie - combat text. Stitch and guards sparring. Deleting standard stitch spawns with Abercrombie and guards. Adding doubles in phase 1 for creatures from phases 3 and 2?

okay

**Pull request closed without merging**
