### PR TITLE
Correct info of Stormwind NPC Leria Nightwind

### PR DESCRIPTION
**Pull request by den13501**
correcting position and posture of Leria Nightwind

### CODE REVIEW

**Comment by fcshden** [comment]
https://www.wowhead.com/npc=61837/leria-nightwind
PIC

**Comment by den13501** [comment]
https://www.wowhead.com/npc=61837/leria-nightwind
PIC

**Comment by alexkulya** [comment]
Thanks for the fix. I apply the fix as soon as I get back home from work. Work on New Years is especially good.

**Comment by den13501** [comment]
No hurry, have a nice vacation 😄

**Pull request merged**
